### ISSUE TITLE
Issue installing styledown2

### ISSUE THREAD

**Issue by nkpgardose** [styledown/styledown2-rails#1]
I'm receiving this error message when running `bundle install`

```sh
Bundler could not find compatible versions for gem "styledown2":
  In Gemfile:
    styledown2-rails was resolved to 2.0.0.pre5, which depends on
      styledown2 (< 3.0.0)

Could not find gem 'styledown2 (< 3.0.0)', which is required by gem 'styledown2-rails', in any of the sources.
```

**Comment by rstacruz** [comment]
Haha, thanks man. Things are still in flux in Styledown2 land. We still don't have a final `v2.0.0` release yet. I'm gonna add `[PREVIEW]` to the projects' descriptions to highlight this...

It seems I forgot to push `styledown2` so it should be okay now.

```rb
# Gemfile
source 'https://rubygems.org'
gem 'styledown2-rails'
```

```
 →  bundle
Fetching gem metadata from https://rubygems.org/...
Fetching version metadata from https://rubygems.org/..
Using execjs 2.7.0
Installing styledown2-source 2.0.0.pre5
Installing styledown2-rails 2.0.0.pre6
Using bundler 1.11.2
Installing styledown2 2.0.0.pre5
Bundle complete! 1 Gemfile dependency, 5 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

:warning: **Styledown2 has a totally new API which hasn't been documented yet** - but for now you can check out:

- [README.md § Install](https://github.com/styledown/styledown2-rails#install)
- [docs/](https://github.com/styledown/styledown2-rails/tree/master/docs)
- [example/](https://github.com/styledown/styledown2-rails/tree/master/example)

**Comment by nkpgardose** [comment]
Thanks man! 👍  I'll check the links.
